# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Algorithm-Annotate
version:      0.10
version_from: Annotate.pm
installdirs:  site
requires:
    Algorithm::Diff:               1.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
